export const stages = [
  "Nuevo prospecto",
  "Asesoría con Sara",
  "Cotización",
  "Confirmación",
];
export const orderStages = [
  "Por autorizar",
  "En producción",
  "Empacado",
  "En tránsito",
  "Entregado",
];
export const sampleStages = [
  "Solicitada",
  "En preparación",
  "Enviada",
  "En evaluación",
  "Evaluada",
];
export function seed() {
  const now = new Date();
  const ago = (days) =>
    new Date(now.getTime() - days * 86400000).toISOString().slice(0, 10);
  return {
    version: 1,
    role: "Administración",
    discountLimit: 0,
    clients: [
      {
        id: "c1",
        name: "Hotel Alameda",
        legal: "",
        rfc: "",
        address: "Av. Ejemplo 120, Monterrey",
        contact: "María López",
        position: "Compras",
        phone: "",
        email: "",
        owner: "Eli",
        lastOrder: ago(17),
        created: ago(20),
        aroma: "",
        notes: "120 habitaciones · Interés en limpieza y aromatización",
        channel: "WhatsApp",
      },
      {
        id: "c2",
        name: "Casa Norte",
        legal: "",
        rfc: "",
        address: "",
        contact: "Carlos Díaz",
        position: "Gerencia",
        phone: "",
        email: "",
        owner: "Vendedor 2",
        lastOrder: ago(36),
        created: ago(60),
        aroma: "",
        notes: "Solicita asesoría sobre espacios comunes",
        channel: "Instagram",
      },
      {
        id: "c3",
        name: "Hotel Mirador",
        legal: "",
        rfc: "",
        address: "",
        contact: "Andrea Gómez",
        position: "Operaciones",
        phone: "",
        email: "",
        owner: "Eli",
        lastOrder: ago(45),
        created: ago(60),
        aroma: "",
        notes: "Seguimiento de recompra",
        channel: "Facebook",
      },
      {
        id: "c4",
        name: "Grupo Horizonte",
        legal: "",
        rfc: "",
        address: "",
        contact: "Sofía García",
        position: "Compras",
        phone: "",
        email: "",
        owner: "Eli",
        lastOrder: null,
        created: ago(3),
        aroma: "",
        notes: "Prefiere evaluar una muestra",
        channel: "WhatsApp",
      },
      {
        id: "c5",
        name: "Hotel del Valle",
        legal: "",
        rfc: "",
        address: "",
        contact: "Lucía Ramos",
        position: "Compras",
        phone: "",
        email: "",
        owner: "Vendedor 2",
        lastOrder: null,
        created: ago(1),
        aroma: "",
        notes: "Solicita precios",
        channel: "Web",
      },
    ],
    opportunities: [
      {
        id: "op1",
        clientId: "c5",
        stage: 0,
        route: "direct",
        amount: 4200,
        next: "Explicar el Sistema ELAH",
        owner: "Sara IA",
        created: ago(1),
      },
      {
        id: "op2",
        clientId: "c2",
        stage: 1,
        route: "direct",
        amount: 3200,
        next: "Confirmar necesidades y aroma",
        owner: "Sara IA",
        created: ago(2),
      },
      {
        id: "op3",
        clientId: "c4",
        stage: 1,
        route: "sample",
        amount: 7600,
        next: "Evaluar resultado de muestra",
        owner: "Eli",
        created: ago(3),
      },
      {
        id: "op4",
        clientId: "c3",
        stage: 2,
        route: "direct",
        amount: 6450,
        next: "Confirmar cantidades",
        owner: "Sara IA",
        created: ago(5),
      },
      {
        id: "op5",
        clientId: "c1",
        stage: 3,
        route: "direct",
        amount: 4800,
        next: "Revisión administrativa",
        owner: "Sara IA",
        created: ago(1),
      },
    ],
    products: [
      {
        id: "p1",
        name: "Limpiador profesional",
        size: "5 L",
        price: 850,
        sku: "HE-LIM-05",
      },
      {
        id: "p2",
        name: "Aromatizante",
        size: "1 L",
        price: 350,
        sku: "HE-ARO-01",
      },
      {
        id: "p3",
        name: "Paquete limpieza + aroma ELAH",
        size: "Paquete",
        price: 1200,
        sku: "HE-ELAH-01",
      },
    ],
    aromas: [],
    quotes: [],
    orders: [
      {
        id: "HE-1048",
        clientId: "c1",
        opportunityId: "op5",
        total: 4800,
        status: "Por autorizar",
        confirmed: true,
        created: ago(1),
        due: ago(-7),
        tracking: "",
        channel: "WhatsApp",
        invoiceAmount: 0,
      },
      {
        id: "HE-1047",
        clientId: "c2",
        total: 3200,
        status: "En producción",
        confirmed: true,
        created: ago(5),
        due: ago(-2),
        tracking: "",
        channel: "Web",
        invoiceAmount: 0,
      },
      {
        id: "HE-1046",
        clientId: "c3",
        total: 6450,
        status: "Empacado",
        confirmed: true,
        created: ago(8),
        due: ago(-1),
        tracking: "",
        channel: "WhatsApp",
        invoiceAmount: 0,
      },
      {
        id: "HE-1045",
        clientId: "c3",
        total: 2400,
        status: "En tránsito",
        confirmed: true,
        created: ago(10),
        due: ago(1),
        tracking: "DEMO-1045",
        channel: "WhatsApp",
        invoiceAmount: 2400,
      },
    ],
    samples: [
      {
        id: "M-0084",
        opportunityId: "op3",
        clientId: "c4",
        status: "En evaluación",
        aroma: "Por confirmar",
        result: "",
        tracking: "DEMO-M0084",
      },
    ],
    appointments: [],
    tasks: [],
    notifications: [],
    audit: [],
    conversations: [
      {
        id: "chat1",
        clientId: "c1",
        human: false,
        messages: [
          {
            by: "Cliente",
            text: "Necesito limpieza y aromatización para mi hotel.",
          },
          {
            by: "Sara IA · Demo",
            text: "Puedo ayudarte a consultar productos y preparar una cotización. La muestra es opcional. ¿Qué áreas y cantidades necesitas?",
          },
        ],
      },
    ],
  };
}
